# Generated by Django 5.1.1 on 2024-10-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut_administrador', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_administrador', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('appaterno', models.CharField(max_length=25)),
                ('apmaterno', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_alumno', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('appaterno', models.CharField(max_length=25)),
                ('apmaterno', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('rut_apoderado', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_apoderado', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('appaterno', models.CharField(max_length=25)),
                ('apmaterno', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'apoderado',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=25)),
                ('anno_generacion', models.IntegerField()),
                ('semestre', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut_profesor', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_profesor', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('appaterno', models.CharField(max_length=25)),
                ('apmaterno', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='TipoAnotacion',
            fields=[
                ('id_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('positiva', models.CharField(blank=True, max_length=1, null=True)),
                ('negativa', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tipo_anotacion',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.CharField(max_length=10)),
                ('nombre_asignatura', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'asignatura',
                'unique_together': {('id_asignatura', 'nombre_asignatura')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('alumno_rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('calificacion', models.FloatField()),
                ('nota_1', models.FloatField()),
                ('nota_2', models.FloatField()),
                ('nota_3', models.FloatField()),
                ('nota_4', models.FloatField()),
                ('promedio', models.IntegerField()),
                ('nota_5', models.FloatField(blank=True, null=True)),
                ('nota_6', models.FloatField(blank=True, null=True)),
                ('alumno_rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('rut_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
                ('tipo_anotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoanotacion')),
            ],
            options={
                'db_table': 'anotacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usuario', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dv_usuario', models.CharField(max_length=1)),
                ('tipo_usuario', models.CharField(max_length=25)),
                ('contrasena', models.CharField(max_length=20)),
                ('rut_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.administrador')),
                ('rut_apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apoderado')),
                ('rut_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ApoderadoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('rut_apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apoderado')),
            ],
            options={
                'db_table': 'apoderado_alumno',
                'unique_together': {('rut_apoderado', 'alumno_rut_alumno')},
            },
        ),
        migrations.CreateModel(
            name='AsignaturaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=25)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('curso_id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('id_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nota')),
            ],
            options={
                'db_table': 'asignatura_curso',
                'unique_together': {('id_asignatura', 'nombre_asignatura', 'curso_id_curso')},
            },
        ),
        migrations.CreateModel(
            name='AsignaturaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=25)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('profesor_rut_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
            options={
                'db_table': 'asignatura_profesor',
                'unique_together': {('id_asignatura', 'nombre_asignatura', 'profesor_rut_profesor')},
            },
        ),
        migrations.CreateModel(
            name='AnnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('rut_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
            options={
                'db_table': 'anno_curso',
                'unique_together': {('rut_alumno', 'id_curso', 'rut_profesor')},
            },
        ),
    ]
